-- RUN THIS IN SUPABASE SQL EDITOR

CREATE TABLE public.leads_pilot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Core Data
    employer_name text,
    broker_firm text,
    broker_human_name text,
    broker_email text,
    state text,
    lives_count integer,
    assets_amount numeric,
    
    -- Verification & Signals (Platinum Spec)
    verification_status text DEFAULT 'UNVERIFIED',
    geo_score integer DEFAULT 0,
    industry_score integer DEFAULT 0,
    search_score integer DEFAULT 0,
    verified_broker_truth text,
    
    -- AI Generation (Bernays)
    psych_profile_json jsonb,
    draft_email_text text,
    
    -- Feedback
    andrew_feedback_score text DEFAULT '0'
);

-- Index for faster lookups
CREATE INDEX idx_leads_employer ON public.leads_pilot (employer_name);
CREATE INDEX idx_leads_status ON public.leads_pilot (verification_status);
